### ISSUE TITLE
Comentarios sobre el ejercicio

### ISSUE THREAD

**Issue by m4n50n** [juliangb44/bootstrap-intafram-feed#1]
Hola Julián,

el ejercicio tiene buena pinta, pero está incompleto. Cuando lo abro se me ve así la parte en la que se tienen que mostrar los post uno a uno:
![image](https://user-images.githubusercontent.com/92524023/201077419-a9f925bf-0e75-4f13-966a-2f3e060a4081.png)

Échale un vistazo cuando puedas y nos lo vuelves a enviar. Cualquier problema nos dices!👍

**Comment by juliangb44** [comment]
Corregido! :)
